"""Seed the unified Bros Cafe product catalog (single source of truth).

Replaces the products collection with the full 17-item catalog used by the
website, shop, loyalty recommendations and product details.
Idempotent: wipes and re-inserts. Run: python seed_catalog.py
"""
import os
from pathlib import Path

from dotenv import load_dotenv
from pymongo import MongoClient

load_dotenv(Path(__file__).parent / ".env")

U = lambda pid: f"https://images.unsplash.com/{pid}?w=900&q=80"
PEX = "https://images.pexels.com/photos"
UP = "https://customer-assets-m6fa6gv7.emergentagent.net/job_premium-cafe-vision/artifacts"

IMG = {
    "espresso": "https://images.unsplash.com/photo-1616388761741-a5936c6f61f6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1NzZ8MHwxfHNlYXJjaHwxfHxzcGVjaWFsdHklMjBjb2ZmZWUlMjBlc3ByZXNzbyUyMHBvdXJpbmd8ZW58MHx8fHwxNzg3NjYzODU1fDA&ixlib=rb-4.1.0&q=85",
    "espresso_close": "https://images.unsplash.com/photo-1475296204602-08d15839e95f?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1NzZ8MHwxfHNlYXJjaHwyfHxzcGVjaWFsdHklMjBjb2ZmZWUlMjBlc3ByZXNzbyUyMHBvdXJpbmd8ZW58MHx8fHwxNzg3NjYzODU1fDA&ixlib=rb-4.1.0&q=85",
    "latte": f"{PEX}/32590864/pexels-photo-32590864.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "latte_art": f"{UP}/bcss9hu4_Gemini_Generated_Image_10kd0510kd0510kd.webp",
    "cappuccino": f"{PEX}/11201494/pexels-photo-11201494.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "americano": "https://images.unsplash.com/photo-1583165278997-0250ea5d72e2?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1NzZ8MHwxfHNlYXJjaHwzfHxzcGVjaWFsdHklMjBjb2ZmZWUlMjBlc3ByZXNzbyUyMHBvdXJpbmd8ZW58MHx8fHwxNzg3NjYzODU1fDA&ixlib=rb-4.1.0&q=85",
    "iced_latte": U("photo-1517701550927-30cf4ba1dba5"),
    "cold_brew": U("photo-1578314675249-a6910f80cc4e"),
    "croissant": U("photo-1555507036-ab1f4038808a"),
    "bread": U("photo-1509440159596-0249088772ff"),
    "sandwich": U("photo-1541519227354-08fa5d50c44d"),
    "waffles": U("photo-1484723091739-30a097e8f929"),
    "sundae": U("photo-1551024506-0bccd828d307"),
    "tee": U("photo-1521572163474-6864f9cf17ab"),
    "hoodie": U("photo-1556821840-3a63f95609a7"),
    "mug": U("photo-1514228742587-6b1558fcca3d"),
    "beans": U("photo-1559056199-641a0ac8b55e"),
    "cafe": "https://images.unsplash.com/photo-1554118811-1e0d58224f24?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA1OTN8MHwxfHNlYXJjaHwxfHxjYWZlJTIwaW50ZXJpb3IlMjBsaWZlc3R5bGUlMjBwZW9wbGV8ZW58MHx8fHwxNzg3NjYzODU1fDA&ixlib=rb-4.1.0&q=85",
    "flatlay": f"{PEX}/32507191/pexels-photo-32507191.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "magazine": "https://images.unsplash.com/photo-1519748771451-a94c596fad67?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NTY2Njd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwbGlmZXN0eWxlJTIwZWRpdG9yaWFsJTIwY29mZmVlfGVufDB8fHx8MTc4NzY2Mzg2M3ww&ixlib=rb-4.1.0&q=85",
    "friends": f"{PEX}/17440526/pexels-photo-17440526.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
}

HERO_VIDEO = "https://assets.mixkit.co/videos/47954/47954-720.mp4"

CATALOG = [
    dict(id="espresso", cat="coffee", order=1, price=3.5, name_en="ESPRESSO", name_hu="ESPRESSO",
         desc_en="Short, dark, honest. The way we judge a café — including our own.",
         desc_hu="Rövid, sötét, őszinte. Ezzel mérünk egy kávézót — magunkat is.",
         image=IMG["espresso"], images=[IMG["espresso"], IMG["espresso_close"], IMG["cafe"]], video=HERO_VIDEO,
         ingredients_en=["18g Bros blend", "Water, 93°C", "27 seconds"],
         ingredients_hu=["18g Bros keverék", "Víz, 93°C", "27 másodperc"],
         flavor={"bitterSweet": 28, "lightBold": 82, "milkyCreamy": 12, "hotIced": 95},
         sizes_en=["Single", "Double"], sizes_hu=["Szimpla", "Dupla"], temp="hot", allergens=[],
         tip_en="Best enjoyed standing at the bar, Italian style.",
         tip_hu="A pultnál állva a legjobb, olasz módra.",
         behind_en=["Beans — our Brazil + Ethiopia blend", "Grind — fine, 18g dose", "Extraction — 27 slow seconds", "Your cup — warmed, always"],
         behind_hu=["Bab — brazil + etióp keverékünk", "Őrlés — finom, 18g adag", "Extrakció — 27 lassú másodperc", "A csészéd — mindig előmelegítve"],
         pairings=["croissant", "bros-beans"]),
    dict(id="cappuccino", cat="coffee", order=2, price=4.5, name_en="CAPPUCCINO", name_hu="CAPPUCCINO",
         desc_en="Rich espresso balanced with silky steamed milk and proper foam.",
         desc_hu="Karakteres espresso, selymesen gőzölt tejjel és rendes habbal.",
         image=IMG["cappuccino"], images=[IMG["cappuccino"], IMG["latte_art"], IMG["magazine"]],
         ingredients_en=["Double espresso", "Steamed milk", "Dense microfoam"],
         ingredients_hu=["Dupla espresso", "Gőzölt tej", "Sűrű mikrohab"],
         flavor={"bitterSweet": 45, "lightBold": 60, "milkyCreamy": 70, "hotIced": 95},
         sizes_en=["Regular", "Large"], sizes_hu=["Normál", "Nagy"], temp="hot", allergens=["Milk"],
         tip_en="Best enjoyed slowly. Ask for oat if that's your thing.",
         tip_hu="Lassan a legjobb. Ha úgy szereted, kérd zabbal.",
         behind_en=["Beans — Brazil + Ethiopia blend", "Espresso — double shot", "Milk — steamed to 60°C", "Foam — spooned, not poured"],
         behind_hu=["Bab — brazil + etióp keverék", "Espresso — dupla shot", "Tej — 60°C-ra gőzölve", "Hab — kanalazva, nem öntve"],
         pairings=["croissant", "banana-bread", "bros-mug"]),
    dict(id="latte", cat="coffee", order=3, price=4.5, name_en="LATTE", name_hu="LATTE",
         desc_en="Milk, done properly. Soft, warm, and gently caffeinated.",
         desc_hu="Tej, rendesen megcsinálva. Lágy, meleg, gyengéden koffeines.",
         image=IMG["latte"], images=[IMG["latte"], IMG["latte_art"], IMG["flatlay"]],
         ingredients_en=["Double espresso", "Lots of steamed milk", "Latte art, if we're not slammed"],
         ingredients_hu=["Dupla espresso", "Sok gőzölt tej", "Latte art, ha nincs rohanás"],
         flavor={"bitterSweet": 55, "lightBold": 35, "milkyCreamy": 88, "hotIced": 90},
         sizes_en=["Regular", "Large"], sizes_hu=["Normál", "Nagy"], temp="hot", allergens=["Milk"],
         tip_en="Perfect for a slow morning and a window seat.",
         tip_hu="Tökéletes egy lassú reggelhez és egy ablak melletti helyhez.",
         behind_en=["Beans — Brazil + Ethiopia blend", "Espresso — double shot", "Milk — silky, glossy steam", "The pour — where the art happens"],
         behind_hu=["Bab — brazil + etióp keverék", "Espresso — dupla shot", "Tej — selymes, fényes gőzölés", "Az öntés — itt történik a varázslat"],
         pairings=["cinnamon-waffles", "bros-mug"]),
    dict(id="americano", cat="coffee", order=4, price=4.0, name_en="AMERICANO", name_hu="AMERICANO",
         desc_en="Clean and slow. Espresso lengthened, flavor intact.",
         desc_hu="Tiszta és lassú. Hosszított espresso, ép ízzel.",
         image=IMG["americano"], images=[IMG["americano"], IMG["espresso"], IMG["cafe"]],
         ingredients_en=["Double espresso", "Hot water"], ingredients_hu=["Dupla espresso", "Forró víz"],
         flavor={"bitterSweet": 35, "lightBold": 55, "milkyCreamy": 5, "hotIced": 85},
         sizes_en=["Regular", "Large"], sizes_hu=["Normál", "Nagy"], temp="both", allergens=[],
         tip_en="Great black. Even better with ten quiet minutes.",
         tip_hu="Feketén remek. Tíz csendes perccel még jobb.",
         behind_en=["Beans — Brazil + Ethiopia blend", "Espresso — double shot", "Water — hot, poured gently", "Crema — kept on top"],
         behind_hu=["Bab — brazil + etióp keverék", "Espresso — dupla shot", "Víz — forrón, óvatosan öntve", "Crema — a tetején marad"],
         pairings=["bros-sandwich", "bros-beans"]),
    dict(id="cold-brew", cat="cold", order=5, price=4.5, name_en="COLD BREW", name_hu="COLD BREW",
         desc_en="Steeped for 18 hours. Smooth, chocolatey, dangerously drinkable.",
         desc_hu="18 órát ázott. Sima, csokis, veszélyesen iható.",
         image=IMG["cold_brew"], images=[IMG["cold_brew"], IMG["iced_latte"], IMG["flatlay"]],
         ingredients_en=["Coarse-ground Bros blend", "Cold water", "Time — 18 hours"],
         ingredients_hu=["Durvára őrölt Bros keverék", "Hideg víz", "Idő — 18 óra"],
         flavor={"bitterSweet": 40, "lightBold": 65, "milkyCreamy": 10, "hotIced": 5},
         sizes_en=["Regular", "Large"], sizes_hu=["Normál", "Nagy"], temp="iced", allergens=[],
         tip_en="Ask for a slice of orange if you like it bright.",
         tip_hu="Kérj hozzá egy szelet narancsot, ha frissen szereted.",
         pairings=["brownie-sundae", "bros-tee"]),
    dict(id="iced-latte", cat="cold", order=6, price=5.0, name_en="ICED LATTE", name_hu="JEGES LATTE",
         desc_en="Espresso over ice, cold milk on top. Summer in a glass.",
         desc_hu="Espresso jégen, hideg tej a tetején. Nyár egy pohárban.",
         image=IMG["iced_latte"], images=[IMG["iced_latte"], IMG["latte"], IMG["magazine"]],
         ingredients_en=["Double espresso", "Ice", "Cold milk"],
         ingredients_hu=["Dupla espresso", "Jég", "Hideg tej"],
         flavor={"bitterSweet": 50, "lightBold": 40, "milkyCreamy": 80, "hotIced": 5},
         sizes_en=["Regular", "Large"], sizes_hu=["Normál", "Nagy"], temp="iced", allergens=["Milk"],
         tip_en="Watch it marble before you stir. Half the fun.",
         tip_hu="Nézd, ahogy márványosodik, mielőtt megkevered. Ez a fele élmény.",
         pairings=["croissant", "brownie-sundae"]),
    dict(id="espresso-tonic", cat="cold", order=7, price=5.5, name_en="ESPRESSO TONIC", name_hu="ESPRESSO TONIC",
         desc_en="Sounds wrong, tastes right. Double shot over tonic and ice.",
         desc_hu="Rossznak hangzik, finom. Dupla shot tonic és jég felett.",
         image=IMG["americano"], images=[IMG["americano"], IMG["espresso_close"], IMG["cafe"]],
         ingredients_en=["Double espresso", "Tonic water", "Ice", "Orange peel"],
         ingredients_hu=["Dupla espresso", "Tonic", "Jég", "Narancshéj"],
         flavor={"bitterSweet": 60, "lightBold": 30, "milkyCreamy": 0, "hotIced": 5},
         sizes_en=["One size"], sizes_hu=["Egy méret"], temp="iced", allergens=[],
         tip_en="Our most argued-about drink. Try it before you judge it.",
         tip_hu="A legtöbbet vitatott italunk. Kóstold meg, mielőtt ítélkezel.",
         pairings=["bros-sandwich"]),
    dict(id="bros-sandwich", cat="food", order=8, price=7.5, name_en="BROS SANDWICH", name_hu="BROS SZENDVICS",
         desc_en="Toasted sourdough, slow fillings, made when you order it.",
         desc_hu="Pirított kovászos kenyér, lassan készült töltelék, rendelésre frissen.",
         image=IMG["sandwich"], images=[IMG["sandwich"], IMG["bread"], IMG["cafe"]],
         ingredients_en=["Sourdough", "Slow-cooked filling of the day", "Greens", "House sauce"],
         ingredients_hu=["Kovászos kenyér", "A nap lassú tölteléke", "Zöldek", "Házi szósz"],
         sizes_en=["One size"], sizes_hu=["Egy méret"], temp="hot", allergens=["Gluten", "Egg"],
         tip_en="The sauce recipe is a secret. We've tried to get it out of them.",
         tip_hu="A szósz receptje titok. Hiába próbáltuk kiszedni belőlük.",
         pairings=["americano", "espresso-tonic"]),
    dict(id="cinnamon-waffles", cat="food", order=9, price=6.5, name_en="WAFFLES", name_hu="GOFRI",
         desc_en="Crisp outside, soft inside, maple doing what maple does.",
         desc_hu="Kívül ropogós, belül puha, a juharszirup teszi a dolgát.",
         image=IMG["waffles"], images=[IMG["waffles"], IMG["sundae"], IMG["flatlay"]],
         ingredients_en=["Buttermilk batter", "Butter", "Maple syrup", "Berries"],
         ingredients_hu=["Írós tészta", "Vaj", "Juharszirup", "Bogyós gyümölcsök"],
         sizes_en=["Half", "Full"], sizes_hu=["Fél adag", "Egész"], temp="hot", allergens=["Gluten", "Milk", "Egg"],
         tip_en="Weekend mornings were invented for this.",
         tip_hu="A hétvégi reggelek ezért lettek kitalálva.",
         pairings=["latte", "cappuccino"]),
    dict(id="croissant", cat="sweet", order=10, price=3.0, name_en="BUTTER CROISSANT", name_hu="VAJAS CROISSANT",
         desc_en="Laminated, golden, and gone by eleven most days.",
         desc_hu="Rétegzett, aranybarna, és a legtöbb nap tizenegyre elfogy.",
         image=IMG["croissant"], images=[IMG["croissant"], IMG["bread"], IMG["magazine"]],
         ingredients_en=["Flour", "A lot of butter", "Time", "Patience"],
         ingredients_hu=["Liszt", "Sok vaj", "Idő", "Türelem"],
         flavor={"bitterSweet": 70, "lightBold": 20, "milkyCreamy": 60, "hotIced": 70},
         sizes_en=["One size"], sizes_hu=["Egy méret"], temp="hot", allergens=["Gluten", "Milk"],
         tip_en="Warm it up. Thank us later.", tip_hu="Melegítsd meg. Később megköszönöd.",
         pairings=["cappuccino", "espresso"]),
    dict(id="banana-bread", cat="sweet", order=11, price=3.5, name_en="BANANA BREAD", name_hu="BANÁNOS KENYÉR",
         desc_en="Dense, toasty, just sweet enough. A Bros classic.",
         desc_hu="Sűrű, pirítós, épp elég édes. Bros klasszikus.",
         image=IMG["bread"], images=[IMG["bread"], IMG["croissant"], IMG["cafe"]],
         ingredients_en=["Overripe bananas", "Brown butter", "Walnuts"],
         ingredients_hu=["Túlérett banán", "Barna vaj", "Dió"],
         flavor={"bitterSweet": 78, "lightBold": 30, "milkyCreamy": 45, "hotIced": 70},
         sizes_en=["Slice", "Two slices (no judgment)"], sizes_hu=["Szelet", "Két szelet (nem ítélkezünk)"],
         temp="hot", allergens=["Gluten", "Egg", "Nuts"],
         tip_en="Toasted with a little salted butter. Trust us.",
         tip_hu="Pirítva, egy kevés sózott vajjal. Bízz bennünk.",
         pairings=["cappuccino", "cold-brew"]),
    dict(id="brownie-sundae", cat="sweet", order=12, price=6.0, name_en="BROWNIE SUNDAY", name_hu="BROWNIE SUNDAY",
         desc_en="Warm brownie, cold ice cream, chocolate everywhere.",
         desc_hu="Meleg brownie, hideg fagyi, csoki mindenhol.",
         image=IMG["sundae"], images=[IMG["sundae"], IMG["waffles"], IMG["flatlay"]],
         ingredients_en=["Double-choc brownie", "Vanilla ice cream", "Warm chocolate sauce"],
         ingredients_hu=["Dupla csokis brownie", "Vanílafagyi", "Meleg csokiszósz"],
         flavor={"bitterSweet": 85, "lightBold": 75, "milkyCreamy": 70, "hotIced": 30},
         sizes_en=["One size"], sizes_hu=["Egy méret"], temp="both", allergens=["Gluten", "Milk", "Egg"],
         tip_en="Share it. Or don't. We're not watching.",
         tip_hu="Oszd meg. Vagy ne. Nem nézünk oda.",
         pairings=["espresso", "cold-brew"]),
    dict(id="bros-tee", cat="merch", order=13, price=28, name_en="BROS TEE", name_hu="BROS PÓLÓ",
         desc_en="Heavyweight cotton, small logo, cream on olive. Wears in beautifully.",
         desc_hu="Nehéz pamut, kis logó, krém olíva alapon. Gyönyörűen kopik.",
         image=IMG["tee"], images=[IMG["tee"], IMG["hoodie"], IMG["cafe"]],
         sizes_en=["S", "M", "L", "XL"], sizes_hu=["S", "M", "L", "XL"],
         material_en="100% organic heavyweight cotton, 240gsm", material_hu="100% bio nehéz pamut, 240g/m²",
         tip_en="Size up for the relaxed café fit.", tip_hu="Vegyél egy számmal nagyobbat a laza kávézós fazonhoz.",
         pairings=["bros-hoodie", "bros-beans"]),
    dict(id="bros-hoodie", cat="merch", order=14, price=58, name_en="BROS HOODIE", name_hu="BROS HOODIE",
         desc_en="The one the staff fight over. Brushed inside, boxy fit.",
         desc_hu="Ezért veszekszik a csapat. Belül bolyhozott, boxy fazon.",
         image=IMG["hoodie"], images=[IMG["hoodie"], IMG["tee"], IMG["friends"]],
         sizes_en=["S", "M", "L", "XL"], sizes_hu=["S", "M", "L", "XL"],
         material_en="Brushed fleece, 400gsm, embroidered logo", material_hu="Bolyhozott polár, 400g/m², hímzett logó",
         tip_en="One of our favorites. It sells out every drop.", tip_hu="Az egyik kedvencünk. Minden dropból elfogy.",
         pairings=["bros-tee", "bros-mug"]),
    dict(id="bros-mug", cat="merch", order=15, price=18, name_en="BROS MUG", name_hu="BROS BÖGRE",
         desc_en="Speckled stoneware, made for slow mornings at home.",
         desc_hu="Pöttyös kőedény, otthoni lassú reggelekre.",
         image=IMG["mug"], images=[IMG["mug"], IMG["latte_art"], IMG["flatlay"]],
         sizes_en=["350ml"], sizes_hu=["350ml"],
         material_en="Hand-glazed stoneware, dishwasher safe", material_hu="Kézzel mázazott kőedény, mosogatógépben mosható",
         tip_en="Pairs suspiciously well with our beans.", tip_hu="Gyanúsan jól passzol a kávébabunkhoz.",
         pairings=["bros-beans", "latte"]),
    dict(id="bros-beans", cat="merch", order=16, price=14, name_en="BROS BEANS — 250G", name_hu="BROS KÁVÉBAB — 250G",
         desc_en="The exact blend we serve. Brazil + Ethiopia, roasted close by.",
         desc_hu="Pontosan az a keverék, amit mi is szervírozunk. Brazília + Etiópia, a közelben pörkölve.",
         image=IMG["beans"], images=[IMG["beans"], IMG["espresso_close"], IMG["cafe"]],
         ingredients_en=["70% Brazil", "30% Ethiopia", "Roasted weekly"],
         ingredients_hu=["70% Brazília", "30% Etiópia", "Hetente pörkölve"],
         flavor={"bitterSweet": 45, "lightBold": 60, "milkyCreamy": 20, "hotIced": 50},
         sizes_en=["Whole bean", "Ground for espresso", "Ground for filter"],
         sizes_hu=["Egész bab", "Espressóhoz őrölve", "Filterhez őrölve"],
         tip_en="Ask us to grind it for your machine. We'll dial it in together.",
         tip_hu="Kérd meg, hogy a gépedre őröljük. Együtt hangoljuk be.",
         pairings=["bros-mug", "espresso"]),
]

def main():
    client = MongoClient(os.environ["MONGO_URL"])
    db = client[os.environ.get("DB_NAME", "test_database")]
    for i, p in enumerate(CATALOG):
        p["category"] = p["cat"]
        p["active"] = True
        p["options"] = p.get("sizes_en", [])
    db.products.delete_many({})
    db.products.insert_many(CATALOG)
    print(f"Seeded unified catalog: {db.products.count_documents({})} products")

if __name__ == "__main__":
    main()
